name: aacimple
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: 2.0.9
  sqflite: 2.3.2
  flex_color_picker: 3.3.1
  image_picker: 1.0.7
  # flutter_sound: 9.2.13
  permission_handler: 11.3.0
  intl: 0.19.0
  audioplayers: ^6.0.0
  flutter_tts: ^4.0.2
  get_storage: ^2.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/phrases/
    
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/ArialTh.ttf
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri.ttf
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma Regular font.ttf
  uses-material-design: true
